### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nubisub** [nubisub/webdevproject#1]
# hadeeeeh
- [x] View & Edit
- [ ] Responsive
- [x] Backend
- [x] Fix Style
- [ ] API ?
- [x] SearchBar width & heigh 100%
- [x] Smooth Landing Page onload animation
- [x] Fix UX
- [x] Fix Color Palette
- [x] Glowing Shadow Box in pricing
- [ ] Share Modal https://morioh.com/p/ae3e4d801712
# CSS mengkeren
- [ ] Navbar  https://www.onetrust.com/
- [ ] button https://codepen.io/yuhomyan/pen/OJMejWJ
- [ ] Slide Preview https://codepen.io/Akimzzy/pen/JjGKMoX
- [ ] Wave https://codepen.io/goodkatz/pen/LYPGxQz
- [ ] Login form https://codepen.io/andytran/pen/RPBdgM
- [ ] Good Porto https://www.taniarascia.com/
- [ ] CSS Design System https://www.youtube.com/watch?v=lRaL-8qZ0mM&t=8358s&ab_channel=freeCodeCamp.org
